---
- name: Remove multiple permissions
  ansible.windows.win_acl:
    path: "{{ item.path }}"
    user: "{{ item.user }}"
    rights: "{{ item.rights }}"
    state: absent
    type: allow
    inherit: ContainerInherit,ObjectInherit
    propagation: None
  loop: "{{ permission_changes }}"
  when: permission_changes is defined
